#!/bin/bash
RELEASES="wshandler wshandler_rpi reporter reporter_rpi"
TARGETDIR="releases"

BUILD="release"

if [[ "$1" == "debug" ]]; then
	BUILD="debug"
fi

mkdir -p $TARGETDIR
for rel in $RELEASES
do
	RELFILE=$rel
	RELPATH=target/$BUILD
	if [[ "$rel" == *_rpi ]]; then
		RELPATH=target/arm-unknown-linux-gnueabihf/$BUILD
		RELFILE=`echo $rel | awk -F_ '{$(NF--)="";print($0)}'`
	fi
	RR=$TARGETDIR/$rel
	mkdir -p $RR/cnf
	cp $RELPATH/$RELFILE $RR
	if [[ "$RELFILE" == "wshandler" ]]; then
		CONFIGFILES="webserver.json mapping.json"
		SERVICENAME="tswshandler"
	elif [[ "$RELFILE" == "reporter" ]]; then
		CONFIGFILES="report.json"
		SERVICENAME="tsreporter"
	fi
	for cf in $CONFIGFILES
	do
		cp cnf/$cf $RR/cnf/
	done
	cp services/$SERVICENAME $RR/
	cd $TARGETDIR >& /dev/null
	tar cf $rel.tar $rel
	rm -rf $rel
	cd - >& /dev/null
	echo "Completed release for $rel"
done
tar cf $TARGETDIR/website.tar website
echo "Completed release for website"
echo "Done"
